graph LR
    host[**Host**
    Linux
    MacOS
    Windows
    CI/CD
    ...]
    make[**Make**
    test
    build
    run
    deploy
    ...
    ]
    host-->make
    make-->docker[Docker
    Compose]
    container(("&nbsp;&nbsp;&nbsp;&nbsp;**Container(s)**&nbsp;&nbsp;&nbsp;&nbsp;
        Go
        Python
        PostgreSQL
        ...
    "))
    docker-->container
