# Reference https://github.com/mermaid-js/mermaid-cli?tab=readme-ov-file#use-dockerpodman
version: '3.8'
services:
  mermaid:
    image: ghcr.io/mermaid-js/mermaid-cli/mermaid-cli
    volumes:
      - type: bind
        source: .
        target: /data
      - type: bind
        source: ../docs/guide/assets
        target: /opt/docs/guide/assets
