graph LR
    host["`**Host**
    Linux
    MacOS
    Windows
    CI/CD
    ...`"]
    make["`**Make**
    test
    build
    run
    deploy
    ...`"]
    host-->make
    make-->docker[Docker
    Compose]
    container(("`**Command**
    &emsp;&emsp;(container)&emsp;&emsp;
    Go
    Python
    PostgreSQL
    ...`"))
    docker-->container
