# Intro
Type "# Let's print out 'Hello, World!' in Go!"
Sleep 500ms
Ctrl+U
Type "# But first, let's make sure the host has Make, Docker, Compose, and not Go"
Sleep 500ms
Ctrl+U
Type "make --version"
Sleep 500ms
Enter
Sleep 2s
Ctrl+L
Type "docker --version"
Sleep 500ms
Enter
Sleep 2s
Ctrl+L
Type "docker compose version"
Sleep 500ms
Enter
Sleep 2s
Ctrl+L
Type "go version"
Sleep 500ms
Enter
Sleep 2s
Ctrl+L
